# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alarm_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Alarm_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 260)
        Dialog.setMinimumSize(QtCore.QSize(400, 260))
        Dialog.setMaximumSize(QtCore.QSize(400, 260))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 361, 211))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tx_hostname = QtWidgets.QLabel(self.groupBox)
        self.tx_hostname.setGeometry(QtCore.QRect(140, 40, 201, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tx_hostname.setFont(font)
        self.tx_hostname.setStyleSheet("")
        self.tx_hostname.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_hostname.setWordWrap(False)
        self.tx_hostname.setObjectName("tx_hostname")
        self.tx_problem = QtWidgets.QLabel(self.groupBox)
        self.tx_problem.setGeometry(QtCore.QRect(140, 70, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tx_problem.setFont(font)
        self.tx_problem.setStyleSheet("")
        self.tx_problem.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_problem.setWordWrap(False)
        self.tx_problem.setObjectName("tx_problem")
        self.tx_threshold = QtWidgets.QLabel(self.groupBox)
        self.tx_threshold.setGeometry(QtCore.QRect(140, 100, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tx_threshold.setFont(font)
        self.tx_threshold.setStyleSheet("")
        self.tx_threshold.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_threshold.setWordWrap(False)
        self.tx_threshold.setObjectName("tx_threshold")
        self.tx_currentstatus = QtWidgets.QLabel(self.groupBox)
        self.tx_currentstatus.setGeometry(QtCore.QRect(140, 130, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tx_currentstatus.setFont(font)
        self.tx_currentstatus.setStyleSheet("")
        self.tx_currentstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_currentstatus.setWordWrap(False)
        self.tx_currentstatus.setObjectName("tx_currentstatus")
        self.tx_timestamp = QtWidgets.QLabel(self.groupBox)
        self.tx_timestamp.setGeometry(QtCore.QRect(140, 160, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tx_timestamp.setFont(font)
        self.tx_timestamp.setStyleSheet("")
        self.tx_timestamp.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_timestamp.setWordWrap(False)
        self.tx_timestamp.setObjectName("tx_timestamp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Alarm"))
        self.label.setText(_translate("Dialog", "Hostname"))
        self.label_2.setText(_translate("Dialog", "Problem"))
        self.label_3.setText(_translate("Dialog", "Threshold"))
        self.label_4.setText(_translate("Dialog", "Current Status"))
        self.label_5.setText(_translate("Dialog", "Timestamp"))
        self.tx_hostname.setText(_translate("Dialog", "TextLabel"))
        self.tx_problem.setText(_translate("Dialog", "TextLabel"))
        self.tx_threshold.setText(_translate("Dialog", "TextLabel"))
        self.tx_currentstatus.setText(_translate("Dialog", "TextLabel"))
        self.tx_timestamp.setText(_translate("Dialog", "TextLabel"))

